apiVersion: v1
kind: Secret
metadata:
  name: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJnaXRsYWIuc2luZ3VsYXJpdHkuY2x1Yjo1MDUwIjp7InVzZXJuYW1lIjoiZGMiLCJwYXNzd29yZCI6Ikd0YXJvb3QyMDE0IiwiYXV0aCI6IlpHTTZSM1JoY205dmRESXdNVFE9In19fQ=="

---
{{ if .Values.frontend.auth }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
data:
  auth: "ZGV2OiRhcHIxJGY2MVZiclFCJHNHbk1pem9PTm96eEZLMkV5N2hGWTAKCg=="
{{ end }}
